name: Terraform Plan and Apply - Azure

on:
  push:
    branches:
      - main

jobs:
  terraform:
    name: Terraform Plan & Apply
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: false

      - name: Terraform Init
        run: terraform init

      - name: Parse MY_AZ_SECRETS JSON and create tfvars file
        run: |
          echo '${{ secrets.MY_AZ_SECRETS }}' > secret.json
          client_id=$(jq -r '.clientId' secret.json)
          cclient_secret=$(jq -r '.clientSecret' secret.json)
          tenant_id=$(jq -r '.tenantId' secret.json)
          subscription_id=$(jq -r '.subscriptionId' secret.json)

          cat > secrets.tfvars <<EOF
          client_id       = "${client_id}"
          client_secret   = "${client_secret}"
          tenant_id       = "${tenant_id}"
          subscription_id = "${subscription_id}"
          EOF

      - name: Terraform Plan
        run: terraform plan -var-file="secrets.tfvars" -out=tfplan

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan
